'use strict';
const EulerBlock = {
    problems: {
        "p0001": "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.",
        "p0002": "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.",
        "p0003": "The prime factors of 13195 are 5, 7, 13 and 29. What is the largest prime factor of the number 600851475143 ?",
        "p0004": "A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99. Find the largest palindrome made from the product of two 3-digit numbers.",
        "p0005": "2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder. What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?",
        "p0006": "The sum of the squares of the first ten natural numbers is 1^2 + 2^2 + ... + 10^2 = 385. The square of the sum of the first ten natural numbers is (1 + 2 + ... + 10)^2 = 55^2 = 3025. Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640. Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.",
        "p0007": "By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13. What is the 10 001st prime number?",
        print: () => {
            for (let i in EulerBlock.problems) {
                if (typeof EulerBlock.problems[i] === 'string') {
                    document.querySelector('body').insertAdjacentHTML('beforeend', '<section id="' + i + '" class="container"><h2>Problem ' + i + '</h2>' +
                        '<p>' + EulerBlock.problems[i] + '</p> ' +
                        '<div><input type="button" class="submit" value="Get result" /></div><div>Result: <input class="result" value="" readonly/></div><blockquote class="euler-comment">Euler\'s quote</blockquote></section>');
                    const script = document.createElement('script');
                    script.src = './solutions/' + i + '.js';
                    document.querySelector('body').appendChild(script);
                }
            }
        }
    },
    success: {
        "p0001": "You are the 821258th person to have solved this problem. This problem had a difficulty rating of 5%.",
        "p0002": "You are the 657088th person to have solved this problem. This problem had a difficulty rating of 5%.",
        "p0003": "You are the 469761st person to have solved this problem. You have earned 1 new award: 'Baby Steps: Solve three problems'. This problem had a difficulty rating of 5%",
        "p0004": "You are the 416714th person to have solved this problem. This problem had a difficulty rating of 5%.",
        "p0005": "You are the 423905th person to have solved this problem. This problem had a difficulty rating of 5%.",
        "p0006": "You are the 426497th person to have solved this problem. This problem had a difficulty rating of 5%.",
        "p0007": "You are the 365183rd person to have solved this problem. This problem had a difficulty rating of 5%.",
        print: (id) => {
            document.querySelector('#' + id + ' .euler-comment').innerHTML = EulerBlock.success[id];
        }
    },
    bindSubmit: (id, callback) => {
        document.querySelector('#' + id + ' .submit').addEventListener('click', callback);
    },
    setResult: (id, value) => {
        document.querySelector('#' + id + ' .result').value = value;
        EulerBlock.success.print(id);
    }
};
EulerBlock.problems.print();
